WITH TMP AS (SELECT ID, PARENT_ID
FROM ECOLI_DATA
WHERE PARENT_ID IN (SELECT ID FROM ECOLI_DATA WHERE PARENT_ID IS NULL)
            )
SELECT ID
FROM ECOLI_DATA
WHERE PARENT_ID	 IN (SELECT ID FROM TMP)